
image: node:18  # Choose the Node.js version that matches your project

pipelines:
  default:
    - step:
        name: Build and Deploy to Firebase
        caches:
          - node
        script:
          - cd frontend-web
          - node -v
          - npm install
          - npm run build  # Adjust the build command as needed
          - npm install -g firebase-tools
          - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
        services:
          - docker
