image: node:18  # Choose the Node.js version that matches your project

pipelines:
  default:
      - step:
          name: 'Build and Test App'
          script:
            - cd frontend-web
            - node -v
            - yarn
            - yarn run build
            - yarn run test:run
      - step:
          name: 'Deployment to Firebase Testing'
          deployment: testing
          trigger: 'manual'
          caches:
            - node
          script:
            - cd frontend-web
            - node -v
            - yarn
            - yarn run build
            - yarn global add firebase-tools
            - firebase deploy --only hosting:testing --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
          services:
            - docker
