image: node:14

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install

    - step:
        name: Build and Deploy to Firebase
        caches:
          - node
        script:
          - npm run build  # Adjust this command based on your project's build process
          - npm install -g firebase-tools
          - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
