image: node:18  # Choose the Node.js version that matches your project

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test App'
          script:
            - cd frontend-web
            - node -v
            - npm install
            - npm run build

    - step:
        name: 'Deployment to Firebase Testing'
        deployment: production
        trigger: 'manual'
        caches:
          - node
        script:
          - cd frontend-web
          - node -v
          - npm install
          - npm run build
          - npm install -g firebase-tools
          - firebase deploy --only hosting:testing --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
        services:
          - docker