image: node:18 # Choose the Node.js version that matches your project

pipelines:
  default:
    - parallel:
        - step:
            name: "Build and Test App"
            script:
              - cd frontend-web
              - node -v
              - npm install
              - npm run build
