image: node:18  # Choose the Node.js version that matches your project

pipelines:
  default:
    - parallel:
      - step:
          name: 'Python Tests'
          image: python:3.9
          script:
            - cd frontend-web  # Replace 'backend' with the directory where your Python code is located
            - python -m venv venv
            - source venv/bin/activate
            - pip freeze > requirements.txt
            - pip install -r requirements.txt  # Install Python dependencies
            - python run_tests.py  # Run your Python tests
      - step:
          name: 'Build and Test App'
          trigger: 'manual'
          script:
            - cd frontend-web
            - node -v
            - npm install
            - npm run build

    - step:
        name: 'Deployment to Firebase Testing'
        deployment: testing
        trigger: 'manual'
        caches:
          - node
        script:
          - cd frontend-web
          - node -v
          - npm install
          - npm run build
          - npm install -g firebase-tools
          - firebase deploy --only hosting:testing --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
        services:
          - docker

