export const enum THEME_NAMES { // not implementing as of now
  LIGHT = "Light",
  DARK = "Dark",
}

export const CONSTANT = {
  DASHBOARD: "Dashboard",
  DASHBOARD_TITLE: "View all your assets status",
  MY_ASSETS: "My Assets",
  ASSETS: "Assets",
  MY_ASSETS_TITLE: "Add and remove assets",
  ASSETS_TITLE: "Information about assets intended for you ",
  BENEFICIARIES: "Beneficiaries",
  BENEFICIARIES_TITLE: "Add and remove beneficiaries",
  VALIDATORS: "Validators",
  VALIDATORS_TITLE: "Manage your validators",
  PULSE_CHECK: "Pulse check",
  PULSE_CHECK_TITLE: "Check your pulse",
  MY_ACCOUNT: "My Account",
  MY_ACCOUNT_TITLE: "Manage your information",
  TESTAMENT: "Testament",
  TESTAMENT_TITLE: "Manage your information",
  VALIDATION: "Validation",
  VALIDATION_TITLE: "View the messages left for you",
  ADMIN: "Users",
  ADMIN_TITLE: "Admin Dashboard",
  SUPER_ADMIN: "Users",
  SUPER_ADMIN_TITLE: "Super Admin Dashboard",
  HELP: "Help",
  HELP_TITLE: "Get the help",
  SETTINGS: "Settings",
  SETTINGS_TITLE: "Account Settings",
  LOGOUT: "Logout",
}

export const ASSET_TYPES = {
  BANK_ACCOUNT: "Bank Account",
  LIFE_INSURANCE: "Life insurance",
  REAL_ESTATE: "Real Estate",
  RETIREMENT_ACCOUNT: "Retirement Account",
  STOCKS: "Stocks",
  BONDS: "Bonds",
  COMPANY_SHARES: "Company Shares",
  INVESTMENT_FUNDS: "Investment Funds",
  BROKERAGE_ACCOUNT: "Brokerage Account",
  CRYPTOCURRENCY_SELF_CUSTODY: "Cryptocurrency (Self-custody)",
  CRYPTOCURRENCY_ONLINE_EXCHANGE: "Cryptocurrency (Online Exchange)",
  SAFETY_BOX: "Safety box",
  PHYSICAL_GOODS: "Physical goods",
  ACCOUNT_PASSWORDS: "Account passwords",
  OTHERS_CUSTOM: "Others (Custom)",
}
