export const ROUTE_CONSTANTS = {
  LOGIN: "/login",
  SIGN_UP: "/signup",
  DASHBOARD: "/dashboard",
  PRICING: "/pricing",
  REGISTER_KEY: "/register",
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  DASHBOARD_ASSETS: "assets",
  DASHBOARD_BENEFICIARIES: "beneficiaries",
  DASHBOARD_VALIDATORS: "validators",
  DASHBOARD_PULSE: "pulse",
  DASHBOARD_ACCOUNT: "account",
  DASHBOARD_HELP: "help",
  DASHBOARD_SETTINGS: "setting",
}
